from . import res_company
from . import maintenance_equipment
from . import product_template
from . import mrp_bom
from . import mrp_bom_line
from . import mrp_production
from . import mrp_workorder
from . import stock_lot
from . import stock_picking
from . import res_partner
from . import pnt_sscc_code
from . import mrp_product_tool
from . import product_bom_template
from . import product_bom_template_line
from . import product_packing_wizard