from . import set_template
from . import set_template_line
from . import product_template
from . import product_product
from . import res_company
from . import product_attribute_value
from . import sale_order
from . import sale_order_line
from . import purchase_order
from . import purchase_order_line
from . import account_move
from . import account_move_line
from . import product_material
from . import mrp_bom
from . import project_project
from . import sale_report
from . import account_invoice_report
