# -*- coding: utf-8 -*-

from . import analytic_distribution_template
from . import account_analytic_account
from . import res_company
from . import account_account
from . import analytic_distribution_parameter
from . import analytic_distribution
from . import analytic_distribution_r1
from . import analytic_distribution_r2
from . import analytic_distribution_r3
from . import analytic_distribution_r4
from . import analytic_distribution_r5
from . import analytic_distribution_r6
from . import analytic_distribution_r7
from . import sale_order_line
from . import stock_move
from . import analytic_distribution_line
from . import analytic_distribution_r8r9
from . import analytic_distribution_r10r11r14r15
from . import analytic_distribution_r12
from . import analytic_distribution_r13
from . import analytic_distribution_r16
from . import analytic_distribution_r161
from . import analytic_distribution_r17
from . import analytic_distribution_r19
from . import analytic_distribution_r20
from . import analytic_distribution_r21
from . import analytic_distribution_r18
from . import analytic_distribution_r181
from . import analytic_distribution_r22
from . import analytic_distribution_r23
from . import account_asset
from . import mrp_maintenance_issue
from . import mrp_production_legacy
