from . import stock_location
from . import product_category
from . import product_template
from . import purchase_order_line
from . import res_company
from . import mig_materialesarticulo
from . import mig_articuloidioma
from . import mig_componentes
from . import mig_embalaje
from . import mig_crearpacking
from . import mig_inventario
from . import res_partner
from . import mig_lineastarifa
from . import product_pricelist
from . import hr_employee
from . import sale_order_line
from . import product_pricelist_item
from . import stock_lot
from . import product_product
from . import stock_quant
from . import stock_picking
