{
    "name": "Custom Inplast",
    "summary": "Customs Inplast",
    "version": "17.0.1.0.0",
    "category": "Product, Picking",
    "author": "Punt Sistemes",
    "website": "https://www.puntsistemes.es",
    "Maintainers": [
        "Equipo rojo",
    ],
    "license": "LGPL-3",
    "depends": [
        "stock",
        "stock_delivery",
        "account",
        "l10n_es_partner",
        "partner_phone_secondary",
        "mrp_lot_as_serial",
        "sale_management",
        "sale_stock",
        "product_supplierinfo_for_customer",
        "product_supplierinfo_for_customer_sale",
        "purchase_order_line_menu",
        "purchase_order_line_receipt_status",
    ],
    "data": [
        "views/stock_location_views.xml",
        "views/res_company_views.xml",
        "views/product_customerinfo_inherit.xml",
        "views/product_category_views.xml",
        "views/product_template_views.xml",
        "views/res_partner_views.xml",
        "views/mig_views.xml",
        "views/stock_lot_views.xml",
        "views/purchase_order_line.xml",
        "security/ir.model.access.csv",
        "views/menu_views.xml",
        "data/server_actions.xml",
        "data/cron_actions.xml",
        "data/decimal_precision.xml",
    ],
    "installable": True,
}
